remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Hyperscope
description: A Venture Capital Firm Focused on Antifragility during the Age of Aquarius
show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
