remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: HYPERSCOPE
description: A Venture Capital Thesis Focused on Antifragility during the Age of Aquarius
# show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
